Get rid of warnings for dual esm and cjs packages of the same version
polkadot-js/common pull request #1890
Opened 2023-10-25 11:03 UTC by forgetso

These warnings are really annoying for dual esm and cjs packages and take up most of the terminal making it hard to debug.

```
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18971) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	esm 12.3.2	node_modules/@polkadot/util/
	cjs 12.3.2	node_modules/@polkadot/util/cjs
@polkadot/types has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	esm 10.9.1	node_modules/@polkadot/types/
	cjs 10.9.1	node_modules/@polkadot/types/cjs
@polkadot/types-create has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	esm 10.9.1	node_modules/@polkadot/types-create/
	cjs 10.9.1	node_modules/@polkadot/types-create/cjs
@polkadot/types-codec has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	esm 10.9.1	node_modules/@polkadot/types-codec/
	cjs 10.9.1	node_modules/@polkadot/types-codec/cjs
@polkadot/util-crypto has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	esm 12.3.2	node_modules/@polkadot/util-crypto/
	cjs 12.3.2	node_modules/@polkadot/util-crypto/cjs
@polkadot/wasm-crypto has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	esm 7.2.2	node_modules/@polkadot/wasm-crypto/
	cjs 7.2.2	node_modules/@polkadot/wasm-crypto/cjs
@polkadot/wasm-bridge has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	esm 7.2.2	node_modules/@polkadot/wasm-bridge/
	cjs 7.2.2	node_modules/@polkadot/wasm-bridge/cjs
@polkadot/wasm-crypto-wasm has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	esm 7.2.2	node_modules/@polkadot/wasm-crypto-wasm/
	cjs 7.2.2	node_modules/@polkadot/wasm-crypto-wasm/cjs
@polkadot/wasm-util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	esm 7.2.2	node_modules/@polkadot/wasm-util/
	cjs 7.2.2	node_modules/@polkadot/wasm-util/cjs

```

This PR removes them when the versions are the same as there is no problem with having both esm and cjs versions installed with the same version number.

2023-10-25 11:39 UTC, forgetso commented
Related https://github.com/polkadot-js/api/issues/5636

2023-10-26 10:05 UTC, jacogr commented
I would rather (as originally suggested in the linked issue), disable it with an env variable.

As it stands, this has personally saved my behind a couple of times. (As obnoxious as it might be).

2023-11-17 09:21 UTC, jacogr approved these changes
Thank you.

2023-11-17 09:27 UTC, jacogr requested changes
One small change to cater for multiple environments.

2023-11-17 09:27 UTC, jacogr commented on packages/util/src/versionDetect.ts
> +  const esmCjsWarningDisabled = POLKADOTJS_DISABLE_ESM_CJS_WARNING_FLAG in process.env && process.env[POLKADOTJS_DISABLE_ESM_CJS_WARNING_FLAG] === '1';
```suggestion
  const esmCjsWarningDisabled = xglobal.process && POLKADOTJS_DISABLE_ESM_CJS_WARNING_FLAG in xglobal.process.env && xglobal.process.env[POLKADOTJS_DISABLE_ESM_CJS_WARNING_FLAG] === '1';
```

This ensures we work in Node, browser and Deno environments. (The Deno has a CI failure)

2023-11-17 10:14 UTC, jacogr commented on packages/util/src/versionDetect.ts
> +  const esmCjsWarningDisabled = POLKADOTJS_DISABLE_ESM_CJS_WARNING_FLAG in process.env && process.env[POLKADOTJS_DISABLE_ESM_CJS_WARNING_FLAG] === '1';
(PS: I would just merge in master as well, it should make it slightly easier, with the above suggestion, after https://github.com/polkadot-js/common/pull/1894)

2023-11-17 19:09 UTC, jacogr approved these changes
Going to merge as-is and apply the fixes in a PR shortly following.

2023-11-17 19:09 UTC, merged