Add bittensor to genericLedgerApps
polkadot-js/common pull request #1941
Opened 2024-09-12 18:15 UTC by camfairchild

Bittensor has applied the runtime upgrade for the generic Ledger app integration.
This PR adds it to the mapping of `genericLedgerApps`

2024-09-12 18:19 UTC, garrett-opentensor approved these changes

2024-09-12 20:00 UTC, TarikGul requested changes
You will also need to add configuration to 

-`packages/networks/src/defaults/genesis.ts`
-`packages/networks/src/defaults/ledger.ts`

2024-09-17 22:10 UTC, camfairchild commented
> You will also need to add configuration to
> 
> -`packages/networks/src/defaults/genesis.ts` -`packages/networks/src/defaults/ledger.ts`

Apologies. I've added the network to `packages/networks/src/defaults/ledger.ts` as it's already in the `genesis.ts`

2024-09-18 12:27 UTC, TarikGul approved these changes

2024-09-18 12:28 UTC, merged